language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - COMPOSER_MEMORY_LIMIT=-1
    - composer self-update
    - if [ "$STABILITY" = "dev" ]; then composer config minimum-stability dev; fi;

install:
    - composer install
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --with-all-dependencies; fi;

script:
    - vendor/bin/phpunit --coverage-text
    - phantomjs Resources/js/run-qunit.js file://`pwd`/Resources/js/index.html
    - phantomjs Resources/js/run-qunit.js file://`pwd`/Resources/js/index-with-es5-shim.html

matrix:
    fast_finish: true
    include:
      - php: 7.2
        env: SYMFONY_VERSION='^4.0'
      - php: 7.2
        env: SYMFONY_VERSION='^5.0'
      - php: 7.2
        env: STABILITY=dev
